version: '3.9'

services:
  app:
    build: .
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./artifacts:/app/artifacts
    command: uvicorn app.api.server:app --host 0.0.0.0 --port 8001
